services:
  - type: web
    name: vayu-backend
    env: node
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SUPABASE_URL
        value: https://kfekjtokxidyohchsinc.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmZWtqdG9reGlkeW9oY2hzaW5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NTI0NTAsImV4cCI6MjA4NjAyODQ1MH0.1GF90cX5LdDgk6nJZyFNNXoPBonwW3UyAageGG5jmXg
      - key: PORT
        value: 10000
